[appConfig]
    address = "0.0.0.0:8080"
[mysqlConfig]
    ipPort = "localhost:3306" 
    userPassword = "root:**********"  
    database = "ataoblog"
[redisconfig]
    addr = "localhost:6379"     
	password ="***********"
	dB   = 0